/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Thursday, November 7, 2019
 ***********************************************************************************************/

#include "inc/utilities/digitaltwin_serializer.h"

//
// Serialize telemetry data
//

bool Esp32AzureKit_SerializePitchTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long pitch = Esp32AzureKit_Telemetry_ReadPitch();

    int neededSize = snprintf(NULL, 0, "%ld", pitch);

    if (neededSize > size - 1)
    {
        LogError("Failed to build pitch payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", pitch);
    }

    return true;
}

bool Esp32AzureKit_SerializeRollTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long roll = Esp32AzureKit_Telemetry_ReadRoll();

    int neededSize = snprintf(NULL, 0, "%ld", roll);

    if (neededSize > size - 1)
    {
        LogError("Failed to build roll payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", roll);
    }

    return true;
}

bool Esp32AzureKit_SerializePressureTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double pressure = Esp32AzureKit_Telemetry_ReadPressure();

    int neededSize = snprintf(NULL, 0, "%f", pressure);

    if (neededSize > size - 1)
    {
        LogError("Failed to build pressure payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", pressure);
    }

    return true;
}

bool Esp32AzureKit_SerializeAltitudeTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double altitude = Esp32AzureKit_Telemetry_ReadAltitude();

    int neededSize = snprintf(NULL, 0, "%f", altitude);

    if (neededSize > size - 1)
    {
        LogError("Failed to build altitude payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", altitude);
    }

    return true;
}

bool Esp32AzureKit_SerializeMagnetXTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetX = Esp32AzureKit_Telemetry_ReadMagnetX();

    int neededSize = snprintf(NULL, 0, "%ld", magnetX);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetX payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetX);
    }

    return true;
}

bool Esp32AzureKit_SerializeMagnetYTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetY = Esp32AzureKit_Telemetry_ReadMagnetY();

    int neededSize = snprintf(NULL, 0, "%ld", magnetY);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetY payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetY);
    }

    return true;
}

bool Esp32AzureKit_SerializeMagnetZTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetZ = Esp32AzureKit_Telemetry_ReadMagnetZ();

    int neededSize = snprintf(NULL, 0, "%ld", magnetZ);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetZ payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetZ);
    }

    return true;
}

bool Esp32AzureKit_SerializeTempTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double temp = Esp32AzureKit_Telemetry_ReadTemp();

    int neededSize = snprintf(NULL, 0, "%f", temp);

    if (neededSize > size - 1)
    {
        LogError("Failed to build temp payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", temp);
    }

    return true;
}

bool Esp32AzureKit_SerializeHumidTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double humid = Esp32AzureKit_Telemetry_ReadHumid();

    int neededSize = snprintf(NULL, 0, "%f", humid);

    if (neededSize > size - 1)
    {
        LogError("Failed to build humid payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", humid);
    }

    return true;
}

bool Esp32AzureKit_SerializeLightTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double light = Esp32AzureKit_Telemetry_ReadLight();

    int neededSize = snprintf(NULL, 0, "%f", light);

    if (neededSize > size - 1)
    {
        LogError("Failed to build light payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", light);
    }

    return true;
}

bool Esp32AzureKit_SerializeMinFreeHeapTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long minFreeHeap = Esp32AzureKit_Telemetry_ReadMinFreeHeap();

    int neededSize = snprintf(NULL, 0, "%ld", minFreeHeap);

    if (neededSize > size - 1)
    {
        LogError("Failed to build minFreeHeap payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", minFreeHeap);
    }

    return true;
}

//
// Serialize read-only property
//

bool Esp32AzureKit_SerializeEchoCommandResponse(char* response, char* payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    int neededSize = snprintf(NULL, 0, "\"%s\"", response);

    if (neededSize > size - 1)
    {
        LogError("Failed to build echo response payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", response);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeModelProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* model = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetModel();

    int neededSize = snprintf(NULL, 0, "\"%s\"", model);

    if (neededSize > size - 1)
    {
        LogError("Failed to build model payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", model);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeSwVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* swVersion = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetSwVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", swVersion);

    if (neededSize > size - 1)
    {
        LogError("Failed to build swVersion payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", swVersion);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeOsNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* osName = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetOsName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", osName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build osName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", osName);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorArchitecture = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetProcessorArchitecture();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorArchitecture);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorArchitecture payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorArchitecture);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorManufacturer = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetProcessorManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorManufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorManufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorManufacturer);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeTotalStorageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalStorage = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetTotalStorage();

    int neededSize = snprintf(NULL, 0, "%ld", totalStorage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalStorage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalStorage);
    }

    return true;
}

bool Urn_azureiot_DeviceManagement_DeviceInformation_SerializeTotalMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalMemory = Urn_azureiot_DeviceManagement_DeviceInformation_Property_GetTotalMemory();

    int neededSize = snprintf(NULL, 0, "%ld", totalMemory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalMemory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalMemory);
    }

    return true;
}

