/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Thursday, November 7, 2019
 ***********************************************************************************************/

#include "inc/utilities/esp32azurekit_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Callback function declarations and DigitalTwin writable (from service side) properties for this interface
//

static void Esp32AzureKitInterface_Property_FanSpeedCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext);

static void Esp32AzureKitInterface_Property_TempThresholdCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext);

//
//  Callback function declarations and DigitalTwin command names for this interface.
//

static void Esp32AzureKitInterface_Command_EchoCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext);

static void Esp32AzureKitInterface_Command_StartFanCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext);

static void Esp32AzureKitInterface_Command_StopFanCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext);

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct ESP32AZUREKIT_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

    double fanSpeed;

    double tempThreshold;

} ESP32AZUREKIT_INTERFACE_STATE;

static ESP32AZUREKIT_INTERFACE_STATE appState;

// Callback function to process the command "echo".
void Esp32AzureKitInterface_Command_EchoCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext)
{
    ESP32AZUREKIT_INTERFACE_STATE* interfaceState = (ESP32AZUREKIT_INTERFACE_STATE*)userInterfaceContext;
    LogInfo("ESP32AZUREKIT_INTERFACE: echo command invoked.");
    LogInfo("ESP32AZUREKIT_INTERFACE: echo request payload=<%.*s>, context=<%p>", (int)commandRequest->requestDataLen, commandRequest->requestData, interfaceState);

    // Get payload string
    char* requestData = (char*)malloc(commandRequest->requestDataLen + 1);
    if (requestData != NULL)
    {
        strncpy(requestData, (char*)commandRequest->requestData, commandRequest->requestDataLen);
        requestData[commandRequest->requestDataLen] = 0;
    }
    else
    {
        LogError("Failed to allocate memory for request payload");
    }

    // Parse request parameters from request payload string
    JSON_Value *jsonValue = NULL;
    jsonValue = json_parse_string((const char*)requestData);

    JSON_Object *jsonPayload = json_value_get_object(jsonValue);
    ESP32AZUREKIT_ECHO_echocommandrequest echocommandrequest;

    mallocAndStrcpy_s(&echocommandrequest.displayedValue, (char*)json_object_get_string(jsonPayload, "displayedValue"));

    // Invoke device command here
    unsigned int statusCode = 200;

    char responsePayload[MAX_MASSAGE_SIZE];

    char* response;

    DIGITALTWIN_COMMAND_RESULT commandResult = Esp32AzureKit_Command_Echo(&echocommandrequest, &response, &statusCode);

    // Serialize command response payload

    if (commandResult == DIGITALTWIN_COMMAND_OK &&
        Esp32AzureKit_SerializeEchoCommandResponse(response, responsePayload, MAX_MASSAGE_SIZE))
    {
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, responsePayload, statusCode);

    }
    else
    {
        LogError("Failed to execute echo command");
        char* errorResponse = "\"Failed to execute echo command\"";
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, errorResponse, statusCode);
    }

    free(requestData);

    if (jsonValue)
    {
        json_value_free(jsonValue);
    }

    if (echocommandrequest.displayedValue != NULL)
    {
        free(echocommandrequest.displayedValue);
    }

}

// Callback function to process the command "startFan".
void Esp32AzureKitInterface_Command_StartFanCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext)
{
    ESP32AZUREKIT_INTERFACE_STATE* interfaceState = (ESP32AZUREKIT_INTERFACE_STATE*)userInterfaceContext;
    LogInfo("ESP32AZUREKIT_INTERFACE: startFan command invoked.");
    LogInfo("ESP32AZUREKIT_INTERFACE: startFan request payload=<%.*s>, context=<%p>", (int)commandRequest->requestDataLen, commandRequest->requestData, interfaceState);

    // Invoke device command here
    unsigned int statusCode = 200;

    DIGITALTWIN_COMMAND_RESULT commandResult = Esp32AzureKit_Command_StartFan(&statusCode);

    if (commandResult == DIGITALTWIN_COMMAND_OK)
    {
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, NULL, statusCode);

    }
    else
    {
        LogError("Failed to execute startFan command");
        char* errorResponse = "\"Failed to execute startFan command\"";
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, errorResponse, statusCode);
    }

}

// Callback function to process the command "stopFan".
void Esp32AzureKitInterface_Command_StopFanCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext)
{
    ESP32AZUREKIT_INTERFACE_STATE* interfaceState = (ESP32AZUREKIT_INTERFACE_STATE*)userInterfaceContext;
    LogInfo("ESP32AZUREKIT_INTERFACE: stopFan command invoked.");
    LogInfo("ESP32AZUREKIT_INTERFACE: stopFan request payload=<%.*s>, context=<%p>", (int)commandRequest->requestDataLen, commandRequest->requestData, interfaceState);

    // Invoke device command here
    unsigned int statusCode = 200;

    DIGITALTWIN_COMMAND_RESULT commandResult = Esp32AzureKit_Command_StopFan(&statusCode);

    if (commandResult == DIGITALTWIN_COMMAND_OK)
    {
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, NULL, statusCode);

    }
    else
    {
        LogError("Failed to execute stopFan command");
        char* errorResponse = "\"Failed to execute stopFan command\"";
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, errorResponse, statusCode);
    }

}

// DigitalTwinSample_ProcessCommandUpdate receives commands from the server.  This implementation acts as a simple dispatcher
// to the functions to perform the actual processing.
void Esp32AzureKitInterface_ProcessCommandUpdate(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* dtCommandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* dtCommandResponse, void* userInterfaceContext)
{
    if (strcmp(dtCommandRequest->commandName, Esp32AzureKitInterface_EchoCommand) == 0)
    {
        Esp32AzureKitInterface_Command_EchoCallback(dtCommandRequest, dtCommandResponse, userInterfaceContext);
        return;
    }

    if (strcmp(dtCommandRequest->commandName, Esp32AzureKitInterface_StartFanCommand) == 0)
    {
        Esp32AzureKitInterface_Command_StartFanCallback(dtCommandRequest, dtCommandResponse, userInterfaceContext);
        return;
    }

    if (strcmp(dtCommandRequest->commandName, Esp32AzureKitInterface_StopFanCommand) == 0)
    {
        Esp32AzureKitInterface_Command_StopFanCallback(dtCommandRequest, dtCommandResponse, userInterfaceContext);
        return;
    }

    // If the command is not implemented by this interface, by convention we return a 501 error to server.
    LogError("ESP32AZUREKIT_INTERFACE: Command name <%s> is not associated with this interface", dtCommandRequest->commandName);
    (void)DigitalTwinClientHelper_SetCommandResponse(dtCommandResponse, "\"Requested command not implemented on this interface\"", 501);
}

// Esp32AzureKitInterface_PropertyCallback is invoked when a property is updated (or failed) going to server.
// ALL property callbacks will be routed to this function and just have the userContextCallback set to the propertyName.
// Product code will potentially have context stored in this userContextCallback.
static void Esp32AzureKitInterface_PropertyCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinReportedStatus, void* userContextCallback)
{
    if (digitalTwinReportedStatus == DIGITALTWIN_CLIENT_OK)
    {
        ReportProperty_Succeeded_Callback("Esp32AzureKit", (const char*)userContextCallback);
        LogInfo("ESP32AZUREKIT_INTERFACE: Updating property=<%s> succeeded", (const char*)userContextCallback);
    }
    else
    {
        ReportProperty_Error_Callback("Esp32AzureKit", (const char*)userContextCallback);
        LogError("ESP32AZUREKIT_INTERFACE: Updating property=<%s> failed, error=<%s>", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinReportedStatus));
    }
}

// Processes a property update, which the server initiated, for 'fanSpeed' property.
static void Esp32AzureKitInterface_Property_FanSpeedCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    ESP32AZUREKIT_INTERFACE_STATE* interfaceState = (ESP32AZUREKIT_INTERFACE_STATE*)userInterfaceContext;

    LogInfo("ESP32AZUREKIT_INTERFACE: fanSpeed property invoked...");
    LogInfo("ESP32AZUREKIT_INTERFACE: fanSpeed data=<%.*s>", (int)dtClientPropertyUpdate->propertyDesiredLen, dtClientPropertyUpdate->propertyDesired);

    DIGITALTWIN_CLIENT_PROPERTY_RESPONSE propertyResponse;

    // Version of this structure for C SDK.
    propertyResponse.version = DIGITALTWIN_CLIENT_PROPERTY_RESPONSE_VERSION_1;
    propertyResponse.responseVersion = dtClientPropertyUpdate->desiredVersion;

    // Parse string value and set updated property
    JSON_Value * jsonValue = json_parse_string((const char*)dtClientPropertyUpdate->propertyDesired);

    double newValue = json_value_get_number(jsonValue);

    bool isTypeValid = (json_value_get_type(jsonValue) == JSONNumber);

    if (isTypeValid)
    {
        interfaceState->fanSpeed = (double)newValue;

        LogInfo("ESP32AZUREKIT_INTERFACE: Updating fanSpeed property with new value <%s> ...", dtClientPropertyUpdate->propertyDesired);
        bool updateResult = Esp32AzureKit_Property_FanSpeedCallback(interfaceState->fanSpeed);
 
        if (updateResult)
        {
            propertyResponse.statusCode = 200;
            propertyResponse.statusDescription = "fanSpeed property is updated successfully";
        }
        else
        {
            LogError("ESP32AZUREKIT_INTERFACE: failed to update writable property fanSpeed...");

            propertyResponse.statusCode = 500;
            propertyResponse.statusDescription = "failed to update writable property";
        }
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: Invalid desired value for fanSpeed, value should be Double");
        propertyResponse.statusCode = 500;
        propertyResponse.statusDescription = "Invalid desired value for fanSpeed, value should be Double";
    }
    json_value_free(jsonValue);

    // DigitalTwin_InterfaceClient_ReportPropertyAsync takes the DIGITALTWIN_CLIENT_PROPERTY_RESPONSE and returns information back to service.
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(appState.interfaceClientHandle, Esp32AzureKitInterface_FanSpeedProperty, 
        (const char*)dtClientPropertyUpdate->propertyDesired, &propertyResponse,
        Esp32AzureKitInterface_PropertyCallback, Esp32AzureKitInterface_FanSpeedProperty);
    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE: DigitalTwin_InterfaceClient_ReportPropertyAsync for fanSpeed failed, error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }
    else
    {
        LogInfo("ESP32AZUREKIT_INTERFACE: Successfully queued property update for fanSpeed");
    }
}

// Processes a property update, which the server initiated, for 'tempThreshold' property.
static void Esp32AzureKitInterface_Property_TempThresholdCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    ESP32AZUREKIT_INTERFACE_STATE* interfaceState = (ESP32AZUREKIT_INTERFACE_STATE*)userInterfaceContext;

    LogInfo("ESP32AZUREKIT_INTERFACE: tempThreshold property invoked...");
    LogInfo("ESP32AZUREKIT_INTERFACE: tempThreshold data=<%.*s>", (int)dtClientPropertyUpdate->propertyDesiredLen, dtClientPropertyUpdate->propertyDesired);

    DIGITALTWIN_CLIENT_PROPERTY_RESPONSE propertyResponse;

    // Version of this structure for C SDK.
    propertyResponse.version = DIGITALTWIN_CLIENT_PROPERTY_RESPONSE_VERSION_1;
    propertyResponse.responseVersion = dtClientPropertyUpdate->desiredVersion;

    // Parse string value and set updated property
    JSON_Value * jsonValue = json_parse_string((const char*)dtClientPropertyUpdate->propertyDesired);

    double newValue = json_value_get_number(jsonValue);

    bool isTypeValid = (json_value_get_type(jsonValue) == JSONNumber);

    if (isTypeValid)
    {
        interfaceState->tempThreshold = (double)newValue;

        LogInfo("ESP32AZUREKIT_INTERFACE: Updating tempThreshold property with new value <%s> ...", dtClientPropertyUpdate->propertyDesired);
        bool updateResult = Esp32AzureKit_Property_TempThresholdCallback(interfaceState->tempThreshold);
 
        if (updateResult)
        {
            propertyResponse.statusCode = 200;
            propertyResponse.statusDescription = "tempThreshold property is updated successfully";
        }
        else
        {
            LogError("ESP32AZUREKIT_INTERFACE: failed to update writable property tempThreshold...");

            propertyResponse.statusCode = 500;
            propertyResponse.statusDescription = "failed to update writable property";
        }
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: Invalid desired value for tempThreshold, value should be Double");
        propertyResponse.statusCode = 500;
        propertyResponse.statusDescription = "Invalid desired value for tempThreshold, value should be Double";
    }
    json_value_free(jsonValue);

    // DigitalTwin_InterfaceClient_ReportPropertyAsync takes the DIGITALTWIN_CLIENT_PROPERTY_RESPONSE and returns information back to service.
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(appState.interfaceClientHandle, Esp32AzureKitInterface_TempThresholdProperty, 
        (const char*)dtClientPropertyUpdate->propertyDesired, &propertyResponse,
        Esp32AzureKitInterface_PropertyCallback, Esp32AzureKitInterface_TempThresholdProperty);
    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE: DigitalTwin_InterfaceClient_ReportPropertyAsync for tempThreshold failed, error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }
    else
    {
        LogInfo("ESP32AZUREKIT_INTERFACE: Successfully queued property update for tempThreshold");
    }
}

// Esp32AzureKitInterface_ProcessPropertyUpdate receives updated properties from the server.  This implementation
// acts as a simple dispatcher to the functions to perform the actual processing.
static void Esp32AzureKitInterface_ProcessPropertyUpdate(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    if (strcmp(dtClientPropertyUpdate->propertyName, Esp32AzureKitInterface_FanSpeedProperty) == 0)
    {
        Esp32AzureKitInterface_Property_FanSpeedCallback(dtClientPropertyUpdate, userInterfaceContext);
        return;
    }

    if (strcmp(dtClientPropertyUpdate->propertyName, Esp32AzureKitInterface_TempThresholdProperty) == 0)
    {
        Esp32AzureKitInterface_Property_TempThresholdCallback(dtClientPropertyUpdate, userInterfaceContext);
        return;
    }

    // If the property is not implemented by this interface, presently we only record a log message but do not have a mechanism to report back to the service
    LogError("ESP32AZUREKIT_INTERFACE: Property name <%s> is not associated with this interface", dtClientPropertyUpdate->propertyName);
}

// Esp32AzureKitInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void Esp32AzureKitInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("Esp32AzureKit", (const char*)userContextCallback);
        LogInfo("ESP32AZUREKIT_INTERFACE: DigitalTwin successfully delivered telemetry message for <%s>", (const char*)userContextCallback);
    }
    else
    {
        SendTelemetry_Error_Callback("Esp32AzureKit", (const char*)userContextCallback);
        LogError("ESP32AZUREKIT_INTERFACE: DigitalTwin failed to deliver telemetry message for <%s>, error=<%s> ", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }
}

// SendTelemetry is a helper function which is periodically invoked by the caller to send telemetry
DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_SendTelemetry_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* telemetryName, const char* telemetryData)
{
    DIGITALTWIN_CLIENT_RESULT result;

    result = DigitalTwin_InterfaceClient_SendTelemetryAsync(interfaceHandle, telemetryName, telemetryData,
        Esp32AzureKitInterface_TelemetryCallback, (void*)telemetryName);

    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending %s", telemetryName);
    }
    else
    {
        LogInfo("ESP32AZUREKIT_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync successfully sent %s", telemetryName);
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple telemetries in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = Esp32AzureKitInterface_Telemetry_SendPitch()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendRoll()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendPressure()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendAltitude()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendMagnetX()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendMagnetY()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendMagnetZ()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendTemp()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendHumid()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendLight()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Esp32AzureKitInterface_Telemetry_SendMinFreeHeap()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("ESP32AZUREKIT_INTERFACE: failed to send telemetries");
    }
    else
    {
        LogInfo("ESP32AZUREKIT_INTERFACE: Queuing of all telemetries to be sent has succeeded");
    }

    return result;
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendPitch()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializePitchTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_PitchTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message pitch failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendRoll()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeRollTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_RollTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message roll failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendPressure()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializePressureTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_PressureTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message pressure failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendAltitude()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeAltitudeTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_AltitudeTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message altitude failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendMagnetX()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeMagnetXTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_MagnetXTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message MagnetX failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendMagnetY()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeMagnetYTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_MagnetYTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message MagnetY failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendMagnetZ()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeMagnetZTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_MagnetZTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message MagnetZ failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendTemp()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeTempTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_TempTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message temp failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendHumid()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeHumidTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_HumidTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message humid failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendLight()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeLightTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_LightTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message light failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Esp32AzureKitInterface_Telemetry_SendMinFreeHeap()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("ESP32AZUREKIT_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Esp32AzureKit_SerializeMinFreeHeapTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Esp32AzureKitInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Esp32AzureKitInterface_MinFreeHeapTelemetry, payloadBuffer);
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: serialize telemetry message minfreeheap failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}


// Esp32AzureKitInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void Esp32AzureKitInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("Esp32AzureKitInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("ESP32AZUREKIT_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("ESP32AZUREKIT_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("ESP32AZUREKIT_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE Esp32AzureKitInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(ESP32AZUREKIT_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(Esp32AzureKitInterfaceId,  Esp32AzureKitInterfaceInstanceName, Esp32AzureKitInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", Esp32AzureKitInterfaceId, Esp32AzureKitInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback(interfaceHandle, Esp32AzureKitInterface_ProcessPropertyUpdate)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE: DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        Esp32AzureKitInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetCommandsCallback(interfaceHandle, Esp32AzureKitInterface_ProcessCommandUpdate)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("ESP32AZUREKIT_INTERFACE: DigitalTwin_InterfaceClient_SetCommandsCallbacks failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        Esp32AzureKitInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("ESP32AZUREKIT_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", Esp32AzureKitInterfaceId, Esp32AzureKitInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void Esp32AzureKitInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
