/*********************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.3.
 *
 * Generated Date: Thursday, November 7, 2019
 *********************************************************************************************/

#ifndef PNP_DEVICE
#define PNP_DEVICE

#include "digitaltwin_device_client_ll.h"
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/tickcounter.h"
#include "inc/utilities/digitaltwin_client_helper.h"

#include "inc/utilities/esp32azurekit_interface.h"

#include "inc/utilities/urn_azureiot_devicemanagement_deviceinformation_interface.h"

#include "inc/esp32AzureKit_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

int pnp_device_initialize(const char* connectionString, const char* trustedCert);

void print_heap_summary(char* sEvent);

void pnp_device_run();

void pnp_device_close();

#ifdef __cplusplus
}
#endif

#endif // PNP_DEVICE
